-- Balanced Spirit Animal assessment templates and immutable user results.
-- Templates are reusable content; each completed result also keeps a snapshot
-- so later template edits never change a user's original report.

create table if not exists public.spirit_animal_report_templates (
  animal_key text primary key,
  animal_name text not null,
  archetype text not null,
  element text not null check (element in ('Fire', 'Earth', 'Air', 'Water')),
  profile_weights jsonb not null default '{}'::jsonb,
  report_data jsonb not null default '{}'::jsonb,
  scoring_version text not null default 'spirit-animal-v1-balanced',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spirit_animal_templates_active_idx
  on public.spirit_animal_report_templates(active);

alter table public.spirit_animal_report_templates enable row level security;

drop policy if exists "public_read_spirit_animal_templates" on public.spirit_animal_report_templates;
create policy "public_read_spirit_animal_templates" on public.spirit_animal_report_templates
  for select using (active = true);

create table if not exists public.spirit_animal_reports (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.users(id) on delete cascade,
  animal_key text not null references public.spirit_animal_report_templates(animal_key),
  status text not null default 'complete' check (status = 'complete'),
  answers jsonb not null default '[]'::jsonb,
  trait_scores jsonb not null default '{}'::jsonb,
  animal_scores jsonb not null default '{}'::jsonb,
  report_snapshot jsonb not null default '{}'::jsonb,
  scoring_version text not null default 'spirit-animal-v1-balanced',
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists spirit_animal_reports_user_id_idx
  on public.spirit_animal_reports(user_id);

create index if not exists spirit_animal_reports_animal_key_idx
  on public.spirit_animal_reports(animal_key);

alter table public.spirit_animal_reports enable row level security;

drop policy if exists "users_own_spirit_animal_reports" on public.spirit_animal_reports;
create policy "users_own_spirit_animal_reports" on public.spirit_animal_reports
  for all using (user_id = auth.uid()::text)
  with check (user_id = auth.uid()::text);

insert into public.spirit_animal_report_templates
  (animal_key, animal_name, archetype, element, profile_weights, report_data)
values
  ('lion', 'Lion', 'The Courageous Guardian', 'Fire', '{"courage":2,"connection":2,"intuition":1,"adaptability":0,"grounding":1,"transformation":0}'::jsonb, '{"animalKey":"lion","animalName":"Lion","emoji":"🦁","archetype":"The Courageous Guardian","element":"Fire","summary":"You move through life with protective courage, warm authority, and a strong instinct to stand up for what matters.","whyThisAnimal":"Your choices favor brave action and loyal connection, supported by practical judgment and a perceptive inner compass.","strengths":["Courage under pressure","Protective loyalty","Natural leadership","Generous confidence"],"shadowPatterns":["Taking on every battle alone","Mistaking vulnerability for weakness","Becoming overly responsible for others"],"relationships":"You love visibly and defend the people in your circle. Your closest bonds grow when leadership becomes partnership and you allow others to support you too.","careerAndPurpose":"You thrive where conviction, responsibility, and visible impact meet: leadership, advocacy, entrepreneurship, coaching, or any role that asks you to rally people around a cause.","lifeLesson":"True strength includes restraint, listening, and the courage to receive care.","guidance":["Choose the battles that protect your deepest values","Invite trusted people into decisions before carrying everything yourself","Use your visibility to make quieter voices safer"],"affirmation":"My courage creates safety, and my open heart makes me strong."}'::jsonb),
  ('bear', 'Bear', 'The Steady Protector', 'Earth', '{"courage":2,"connection":1,"intuition":0,"adaptability":0,"grounding":2,"transformation":1}'::jsonb, '{"animalKey":"bear","animalName":"Bear","emoji":"🐻","archetype":"The Steady Protector","element":"Earth","summary":"Your power is calm, self-contained, and dependable. You create safety by staying rooted when others feel uncertain.","whyThisAnimal":"Your answers combine courage with grounded patience, then add loyalty and a readiness to grow through difficult seasons.","strengths":["Steady resilience","Practical protection","Healthy independence","Patient strength"],"shadowPatterns":["Withdrawing for too long","Carrying burdens without asking for help","Resisting change until it becomes unavoidable"],"relationships":"You show love through consistency, protection, and tangible care. Clear communication helps others understand the depth beneath your quiet exterior.","careerAndPurpose":"You suit work that rewards stamina, stewardship, and sound judgment, including operations, healing, finance, land-based work, management, or building lasting systems.","lifeLesson":"Rest is not retreat when it renews your ability to meet life fully.","guidance":["Protect regular solitude without disappearing from your relationships","Break heavy responsibilities into steady, visible steps","Let change arrive gradually rather than waiting for a crisis"],"affirmation":"I trust my pace, protect my peace, and move with steady power."}'::jsonb),
  ('eagle', 'Eagle', 'The Far-Seeing Pioneer', 'Fire', '{"courage":2,"connection":0,"intuition":2,"adaptability":1,"grounding":0,"transformation":1}'::jsonb, '{"animalKey":"eagle","animalName":"Eagle","emoji":"🦅","archetype":"The Far-Seeing Pioneer","element":"Fire","summary":"You are drawn to altitude: the wider view, the bold direction, and the possibility others have not yet recognized.","whyThisAnimal":"Your responses join courage with intuition and show an ability to adjust as a larger vision takes shape.","strengths":["Strategic vision","Decisive independence","Pattern recognition","Purposeful ambition"],"shadowPatterns":["Living too far in the future","Impatience with small details","Keeping emotional distance while pursuing a goal"],"relationships":"You need honesty, space, and a shared sense of direction. Bonds deepen when you come down from the overview and stay present with everyday feelings.","careerAndPurpose":"You excel in strategy, innovation, leadership, research, creative direction, and ventures where a clear vision must become action.","lifeLesson":"A vision becomes meaningful when it remains connected to people and the present moment.","guidance":["Translate every big vision into one grounded next step","Ask what detail could change the whole picture","Make room for relationships that challenge your perspective"],"affirmation":"I see clearly, choose bravely, and bring my vision to earth."}'::jsonb),
  ('horse', 'Horse', 'The Free-Hearted Pathfinder', 'Fire', '{"courage":2,"connection":1,"intuition":0,"adaptability":2,"grounding":1,"transformation":0}'::jsonb, '{"animalKey":"horse","animalName":"Horse","emoji":"🐎","archetype":"The Free-Hearted Pathfinder","element":"Fire","summary":"Freedom, honest momentum, and lived experience are central to your nature. You learn by moving and meeting life directly.","whyThisAnimal":"Your answers emphasize brave movement and adaptability, balanced by loyalty and enough grounding to carry others with you.","strengths":["Independent drive","Vitality and momentum","Authentic expression","Responsive leadership"],"shadowPatterns":["Running when stillness feels uncomfortable","Overcommitting to preserve every option","Confusing limits with loss of freedom"],"relationships":"You need bonds that offer trust without control. You are deeply loyal when your autonomy is respected and intentions are spoken plainly.","careerAndPurpose":"Dynamic, people-facing, entrepreneurial, travel, performance, sport, and change-oriented roles let your energy become useful rather than restless.","lifeLesson":"Commitment can give your freedom direction instead of taking it away.","guidance":["Choose one meaningful direction before accelerating","Build rhythms that support movement without trapping it","Tell people when you need space instead of simply pulling away"],"affirmation":"I move freely, commit consciously, and carry my truth forward."}'::jsonb),
  ('wolf', 'Wolf', 'The Instinctive Ally', 'Water', '{"courage":0,"connection":2,"intuition":2,"adaptability":1,"grounding":0,"transformation":1}'::jsonb, '{"animalKey":"wolf","animalName":"Wolf","emoji":"🐺","archetype":"The Instinctive Ally","element":"Water","summary":"You balance strong intuition with devotion to your chosen circle. You notice subtle shifts and understand the power of belonging.","whyThisAnimal":"Your pattern centers connection and instinct, with flexibility and renewal helping you protect what matters without becoming rigid.","strengths":["Loyal collaboration","Emotional perception","Strong instincts","Protective intelligence"],"shadowPatterns":["Testing loyalty instead of naming your needs","Absorbing the group''s emotional climate","Feeling torn between independence and belonging"],"relationships":"You form deep bonds and value trust earned over time. Relationships flourish when you keep a clear identity inside the pack.","careerAndPurpose":"You thrive in collaborative strategy, community-building, counseling, investigation, teaching, and roles where reading people matters.","lifeLesson":"Belonging is strongest when it allows individuality, boundaries, and honest change.","guidance":["Name your needs before resentment has time to grow","Trust your first signal, then check it against evidence","Choose communities that welcome both loyalty and independence"],"affirmation":"I trust my instincts and belong without abandoning myself."}'::jsonb),
  ('elephant', 'Elephant', 'The Wise Keeper', 'Earth', '{"courage":1,"connection":2,"intuition":1,"adaptability":0,"grounding":2,"transformation":0}'::jsonb, '{"animalKey":"elephant","animalName":"Elephant","emoji":"🐘","archetype":"The Wise Keeper","element":"Earth","summary":"You carry memory, responsibility, and care with unusual depth. Your steady presence helps people feel held and remembered.","whyThisAnimal":"Your answers place connection and grounded responsibility at the center, supported by quiet courage and perceptive wisdom.","strengths":["Long-term loyalty","Emotional steadiness","Collective wisdom","Responsible care"],"shadowPatterns":["Holding old pain too faithfully","Feeling responsible for everyone''s wellbeing","Keeping traditions that no longer serve"],"relationships":"You value continuity and show love through remembrance, practical help, and presence. Boundaries keep care from turning into exhaustion.","careerAndPurpose":"Mentoring, education, care work, institutional leadership, history, family enterprise, and long-range planning suit your patient influence.","lifeLesson":"Honor the past without asking it to decide the future.","guidance":["Keep the lesson and release the weight of old stories","Let others carry their fair share","Create rituals that support the life you are building now"],"affirmation":"My wisdom has roots, and my heart has room for the future."}'::jsonb),
  ('dolphin', 'Dolphin', 'The Joyful Connector', 'Water', '{"courage":1,"connection":2,"intuition":0,"adaptability":2,"grounding":1,"transformation":0}'::jsonb, '{"animalKey":"dolphin","animalName":"Dolphin","emoji":"🐬","archetype":"The Joyful Connector","element":"Water","summary":"You connect through curiosity, emotional intelligence, and play. Your flexibility helps groups find hope and move together.","whyThisAnimal":"Your choices favor connection and adaptability, with courage and grounded care giving substance to your lightness.","strengths":["Social intelligence","Creative communication","Playful resilience","Cooperative problem-solving"],"shadowPatterns":["Using humor to avoid difficult feelings","Scattering energy across too many people","Adapting so much that your own preference gets lost"],"relationships":"Communication is your bridge. You need warmth, mental movement, and enough emotional honesty that play never has to hide pain.","careerAndPurpose":"Communication, facilitation, design, teaching, media, hospitality, teamwork, and human-centered innovation can turn your social gifts into impact.","lifeLesson":"Joy becomes durable when it makes room for depth, limits, and honest emotion.","guidance":["Ask what you want before adjusting to the room","Use play to open difficult conversations, then stay for the truth","Protect quiet time so your social energy can renew"],"affirmation":"My joy connects, my truth deepens, and my presence helps life move."}'::jsonb),
  ('owl', 'Owl', 'The Quiet Seer', 'Air', '{"courage":0,"connection":1,"intuition":2,"adaptability":0,"grounding":2,"transformation":1}'::jsonb, '{"animalKey":"owl","animalName":"Owl","emoji":"🦉","archetype":"The Quiet Seer","element":"Air","summary":"You seek the truth beneath appearances. Stillness, observation, and careful timing are among your strongest forms of power.","whyThisAnimal":"Your answers combine intuition with grounded discernment, strengthened by meaningful connection and an openness to transformation.","strengths":["Deep observation","Discernment","Independent thought","Calm insight"],"shadowPatterns":["Observing instead of participating","Overthinking signals that were already clear","Appearing distant while processing deeply"],"relationships":"You bond through depth, honesty, and intellectual or spiritual intimacy. Sharing your process prevents silence from being misunderstood.","careerAndPurpose":"Research, analysis, psychology, writing, strategy, healing, and specialist roles reward your ability to see what others miss.","lifeLesson":"Wisdom must eventually leave the private mind and enter lived experience.","guidance":["Act when the pattern is clear enough rather than perfectly proven","Explain your silence to the people who care about you","Pair solitary insight with one trusted conversation"],"affirmation":"I see beneath the surface and share my wisdom at the right time."}'::jsonb),
  ('snake', 'Snake', 'The Alchemist', 'Water', '{"courage":1,"connection":0,"intuition":2,"adaptability":1,"grounding":0,"transformation":2}'::jsonb, '{"animalKey":"snake","animalName":"Snake","emoji":"🐍","archetype":"The Alchemist","element":"Water","summary":"You are built for renewal. You sense when a cycle has ended and possess the courage to shed what no longer fits.","whyThisAnimal":"Your answers strongly join intuition with transformation, supported by flexible action and the bravery to cross thresholds.","strengths":["Regenerative power","Emotional depth","Instinctive timing","Capacity for reinvention"],"shadowPatterns":["Changing everything when one honest adjustment would do","Guarding vulnerability through secrecy","Remaining in transition without choosing a new form"],"relationships":"You need emotional truth and room to evolve. Trust grows when transformation is communicated rather than revealed only after it is complete.","careerAndPurpose":"Healing, crisis work, research, transformation strategy, arts, psychology, and roles involving reinvention can channel your depth.","lifeLesson":"Release is complete only when it creates room for a conscious new choice.","guidance":["Name what is ending before planning what comes next","Let one trusted person witness your process","Use intuition to guide change and evidence to shape its form"],"affirmation":"I release with wisdom and renew myself with intention."}'::jsonb),
  ('fox', 'Fox', 'The Resourceful Strategist', 'Air', '{"courage":0,"connection":0,"intuition":1,"adaptability":2,"grounding":1,"transformation":2}'::jsonb, '{"animalKey":"fox","animalName":"Fox","emoji":"🦊","archetype":"The Resourceful Strategist","element":"Air","summary":"You read situations quickly and find elegant paths through complexity. Intelligence becomes your form of adaptability.","whyThisAnimal":"Your pattern emphasizes adaptation and reinvention, steadied by practical awareness and a keen intuitive read of context.","strengths":["Resourceful thinking","Situational awareness","Creative strategy","Independent problem-solving"],"shadowPatterns":["Keeping too many contingency plans","Hiding uncertainty behind cleverness","Moving on before trust has time to form"],"relationships":"You value wit, independence, and emotional intelligence. Letting others see the plan—and the feeling beneath it—builds stronger trust.","careerAndPurpose":"Strategy, product work, entrepreneurship, negotiation, communications, technology, and complex problem-solving fit your agile mind.","lifeLesson":"Resourcefulness is most powerful when it serves a clear value rather than constant escape.","guidance":["Choose the simplest plan that protects what matters","Share your reasoning instead of expecting others to infer it","Stay long enough to learn what consistency can reveal"],"affirmation":"I adapt with clarity and use my intelligence in service of what matters."}'::jsonb),
  ('butterfly', 'Butterfly', 'The Graceful Renewer', 'Air', '{"courage":1,"connection":1,"intuition":0,"adaptability":2,"grounding":0,"transformation":2}'::jsonb, '{"animalKey":"butterfly","animalName":"Butterfly","emoji":"🦋","archetype":"The Graceful Renewer","element":"Air","summary":"Your gift is becoming. You sense emerging possibilities and help change feel lighter, more beautiful, and more human.","whyThisAnimal":"Your responses favor adaptation and transformation, while connection and courage help your growth inspire rather than isolate.","strengths":["Creative renewal","Hopeful perspective","Sensitivity to possibility","Grace through transition"],"shadowPatterns":["Rushing the uncomfortable middle of change","Chasing novelty instead of completing a cycle","Underestimating the structure transformation needs"],"relationships":"You bring freshness and inspiration to love. Stable bonds grow when others can trust that change will include communication and follow-through.","careerAndPurpose":"Creative work, branding, design, education, wellbeing, change communication, and community initiatives benefit from your ability to reframe experience.","lifeLesson":"Transformation needs a container: time, practice, and the courage to remain present between identities.","guidance":["Give each new direction a clear season of commitment","Celebrate small evidence of growth","Keep one grounding ritual while other parts of life change"],"affirmation":"I welcome change, honor the process, and unfold in my own time."}'::jsonb),
  ('deer', 'Deer', 'The Gentle Wayfinder', 'Earth', '{"courage":0,"connection":0,"intuition":1,"adaptability":1,"grounding":2,"transformation":2}'::jsonb, '{"animalKey":"deer","animalName":"Deer","emoji":"🦌","archetype":"The Gentle Wayfinder","element":"Earth","summary":"You navigate with sensitivity, calm awareness, and quiet resilience. Gentleness is one of your most accurate forms of intelligence.","whyThisAnimal":"Your choices combine grounding with growth, guided by adaptability and a finely tuned awareness of subtle signals.","strengths":["Gentle discernment","Calm responsiveness","Respectful boundaries","Quiet resilience"],"shadowPatterns":["Avoiding necessary confrontation","Becoming hyper-alert to other people''s moods","Mistaking gentleness for an obligation to yield"],"relationships":"You offer tenderness and attentive care. You feel safest where kindness includes directness and boundaries are respected without drama.","careerAndPurpose":"Counseling, care, craft, nature, mediation, detail-rich creative work, and supportive leadership suit your calm influence.","lifeLesson":"Gentleness and firmness can live in the same choice.","guidance":["Say the clear thing before discomfort becomes fear","Return to your body when the room feels emotionally loud","Choose environments where sensitivity is treated as skill"],"affirmation":"I move gently, choose clearly, and trust my quiet strength."}'::jsonb)
on conflict (animal_key) do update set
  animal_name = excluded.animal_name,
  archetype = excluded.archetype,
  element = excluded.element,
  profile_weights = excluded.profile_weights,
  report_data = excluded.report_data,
  scoring_version = excluded.scoring_version,
  active = true,
  updated_at = now();
