-- Replace blended Aura archetypes with distinct single-word labels.

with archetypes(id, archetype) as (
  values
    ('Red', 'Activator'),
    ('Orange', 'Creator'),
    ('Yellow', 'Optimist'),
    ('Green', 'Healer'),
    ('Blue', 'Communicator'),
    ('Indigo', 'Mystic'),
    ('Violet', 'Visionary'),
    ('White', 'Sage'),
    ('Red-Orange', 'Dynamo'),
    ('Red-Yellow', 'Commander'),
    ('Red-Green', 'Guardian'),
    ('Red-Blue', 'Advocate'),
    ('Red-Indigo', 'Strategist'),
    ('Red-Violet', 'Alchemist'),
    ('Red-White', 'Sentinel'),
    ('Orange-Red', 'Performer'),
    ('Orange-Yellow', 'Enthusiast'),
    ('Orange-Green', 'Harmonizer'),
    ('Orange-Blue', 'Storyteller'),
    ('Orange-Indigo', 'Enchanter'),
    ('Orange-Violet', 'Muse'),
    ('Orange-White', 'Inspirer'),
    ('Yellow-Red', 'Achiever'),
    ('Yellow-Orange', 'Spark'),
    ('Yellow-Green', 'Mentor'),
    ('Yellow-Blue', 'Teacher'),
    ('Yellow-Indigo', 'Analyst'),
    ('Yellow-Violet', 'Philosopher'),
    ('Yellow-White', 'Luminary'),
    ('Green-Red', 'Protector'),
    ('Green-Orange', 'Nurturer'),
    ('Green-Yellow', 'Cultivator'),
    ('Green-Blue', 'Counselor'),
    ('Green-Indigo', 'Empath'),
    ('Green-Violet', 'Weaver'),
    ('Green-White', 'Peacemaker'),
    ('Blue-Red', 'Mediator'),
    ('Blue-Orange', 'Expressor'),
    ('Blue-Yellow', 'Messenger'),
    ('Blue-Green', 'Listener'),
    ('Blue-Indigo', 'Oracle'),
    ('Blue-Violet', 'Poet'),
    ('Blue-White', 'Clarifier'),
    ('Indigo-Red', 'Investigator'),
    ('Indigo-Orange', 'Magician'),
    ('Indigo-Yellow', 'Seer'),
    ('Indigo-Green', 'Decoder'),
    ('Indigo-Blue', 'Insight'),
    ('Indigo-Violet', 'Prophet'),
    ('Indigo-White', 'Channel'),
    ('Violet-Red', 'Transformer'),
    ('Violet-Orange', 'Artist'),
    ('Violet-Yellow', 'Dreamer'),
    ('Violet-Green', 'Devotee'),
    ('Violet-Blue', 'Harmonist'),
    ('Violet-Indigo', 'Illuminator'),
    ('Violet-White', 'Ascendant'),
    ('White-Red', 'Purifier'),
    ('White-Orange', 'Blesser'),
    ('White-Yellow', 'Beacon'),
    ('White-Green', 'Restorer'),
    ('White-Blue', 'Whisperer'),
    ('White-Indigo', 'Clairvoyant'),
    ('White-Violet', 'Enlightener')
)
update public.aura_color_report_templates templates
set
  archetype = archetypes.archetype,
  report_data = jsonb_set(
    coalesce(templates.report_data, '{}'::jsonb),
    '{auraArchetype}',
    to_jsonb(archetypes.archetype),
    true
  ),
  updated_at = now()
from archetypes
where templates.id = archetypes.id;
